import { PortraitBust } from "../components/PortraitBust";
import { LINKS } from "../lib/links";
import { galleryAgents, type Portrait } from "../data/gallery";

function PortraitView({ portrait }: { portrait: Portrait }) {
  const canDo = portrait.canDo.map((c) => (c.asksFirst ? `${c.label} (asks first)` : c.label));
  const alone = portrait.doesOnItsOwn.map((a) =>
    a.asksFirst ? `${a.when}: ${a.does} (asks first)` : `${a.when}: ${a.does}`,
  );
  const cannot = portrait.cannot.map((r) => `${r.label} (${r.tool} disabled)`);

  return (
    <div>
      <PortraitBust portrait={portrait} />
      <div className="bg-paper-deep p-6 md:p-8">
        <dl className="space-y-3 text-sm">
          <PortraitFacts label="Can do" items={canDo} />
          {portrait.canTouch.length ? (
            <PortraitFacts label="Can touch" items={portrait.canTouch} />
          ) : null}
          {alone.length ? <PortraitFacts label="Does on its own" items={alone} /> : null}
          {portrait.subagents.length ? (
            <PortraitFacts label="Delegates to" items={portrait.subagents} />
          ) : null}
          {cannot.length ? <PortraitFacts label="Cannot" items={cannot} /> : null}
        </dl>
        <p className="mt-4 text-xs text-ink-soft">{portrait.provenance}</p>
      </div>
    </div>
  );
}

function PortraitFacts({ label, items }: { label: string; items: string[] }) {
  return (
    <div>
      <dt className="eyebrow">{label}</dt>
      <dd className="mt-1 text-ink-soft">{items.join(" · ")}</dd>
    </div>
  );
}

export function GalleryPage() {
  return (
    <div className="mx-auto max-w-6xl px-5 py-16 md:px-8 md:py-20">
      <p className="eyebrow fade-up">Gallery</p>
      <h1 className="display fade-up-delay mt-4 max-w-3xl text-4xl md:text-6xl">
        Portraits of agents you can defend.
      </h1>
      <p className="lead fade-up-delay-2 mt-6">
        Each portrait is generated by <code>aletheia portrait</code> from the agent's
        build, and each "Kit Certified" badge is backed by a passport you can{" "}
        <a className="content-inline-link" href="/passports/design-qa-agent.json">
          fetch and verify
        </a>
        . Nothing here is a screenshot, and this site never hosts your agent source.
      </p>

      <div className="mt-14 grid gap-8">
        {galleryAgents.map((agent) => (
          <article
            key={agent.name}
            className="panel overflow-hidden md:grid md:grid-cols-2"
            aria-label={
              agent.stamped
                ? `${agent.name}, Kit Certified`
                : `${agent.name}, not yet certified`
            }
          >
            <PortraitView portrait={agent.portrait} />
            <div className="flex flex-col justify-center p-8 md:p-10">
              <div className="flex flex-wrap items-center gap-3">
                <p className="eyebrow">{agent.role}</p>
                {agent.stamped ? (
                  <a
                    href={agent.passportUrl}
                    className="rounded-full bg-lime/40 px-3 py-1 text-xs font-medium tracking-wide text-ink no-underline"
                    title="View the passport backing this badge"
                  >
                    Kit Certified
                  </a>
                ) : (
                  <span
                    className="rounded-full border border-ink/20 px-3 py-1 text-xs font-medium tracking-wide text-ink-soft"
                    title={
                      agent.pendingChecks.length
                        ? `Pending: ${agent.pendingChecks.join("; ")}`
                        : undefined
                    }
                  >
                    Not yet certified
                  </span>
                )}
              </div>
              <h2 className="mt-3 text-3xl tracking-tight">{agent.name}</h2>
              <p className="mt-4 text-base leading-relaxed text-ink-soft">{agent.body}</p>
              {!agent.stamped && agent.pendingChecks.length ? (
                <p className="mt-3 text-sm text-ink-soft">
                  Passport pending: {agent.pendingChecks.join("; ")}.
                </p>
              ) : null}
              <div className="mt-8 flex flex-wrap gap-3">
                <a className="btn btn-primary" href={agent.repo}>
                  View repo
                </a>
                <a className="btn btn-secondary" href={agent.portraitUrl}>
                  Portrait JSON
                </a>
                <a className="btn btn-secondary" href={LINKS.aletheia}>
                  Inspect in Aletheia
                </a>
              </div>
            </div>
          </article>
        ))}
      </div>
    </div>
  );
}
